data descriptor as fileUsageRole
HumanBrainProject/openMINDS_instances pull request #19
Opened 2021-05-10 15:50 UTC by UlrikeS91

as discussed with @lzehl

2021-05-10 16:46 UTC, lzehl requested changes

2021-05-10 16:46 UTC, lzehl commented on instances/fileUsageRole/dataDescriptor.jsonld
> +  "definition": "A data descriptor is a document that provides detailed descriptions of research datasets that focus on helping others reuse data.",
Ich würde das tatsächlich so schreiben:
```
"definition": "A 'data descriptors' describes the provenance, the structure, the applied quality assessment, and possible (re)usage of the data. It should not present hypotheses tests, new interpretations, new methods or in-depth analyses."
```

2021-05-10 16:48 UTC, lzehl commented on instances/fileUsageRole/dataDescriptor.jsonld
> +  "definition": "A data descriptor is a document that provides detailed descriptions of research datasets that focus on helping others reuse data.",
I'm getting confused with the languages :sweat_smile: my apologies to all that do not speak German :see_no_evil:

2021-05-10 18:50 UTC, UlrikeS91 commented on instances/fileUsageRole/dataDescriptor.jsonld
> +  "definition": "A data descriptor is a document that provides detailed descriptions of research datasets that focus on helping others reuse data.",
Sounds good. I changed it :)

2021-05-11 06:24 UTC, lzehl approved these changes

2021-05-11 06:24 UTC, merged